const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();

const activeDispatchedAt = minutesAgo(7);
const activeAcceptedAt = minutesAgo(4);
const activeReportReceivedAt = minutesAgo(16);
const activeIncidentTime = minutesAgo(24);
const resolvedDispatchedAt = minutesAgo(190);
const resolvedAcceptedAt = minutesAgo(184);
const resolvedArrivedAt = minutesAgo(160);
const resolvedAt = minutesAgo(118);
const resolvedReturnedAt = minutesAgo(92);
const pendingReportReceivedAt = minutesAgo(12);
const resolvedReportReceivedAt = minutesAgo(205);
const resolvedIncidentTime = minutesAgo(218);

export const DEMO_INCIDENT_REPORTS = [
  {
    id: 'demo-report-flood-pending',
    client_request_id: 'demo-client-request-flood-001',
    lifecycle_revision: 1,
    evidence_status: 'ready',
    type: 'Flood',
    title: 'Rising floodwater near Bigte Bridge',
    specifics: 'Water is rising beside the bridge after heavy rain.',
    description: 'Floodwater is rising beside Bigte Bridge. A family with children is asking for help moving to higher ground.',
    status: 'pending',
    send_to: 'mdrrmo',
    is_escalated: false,
    beyond_barangay_capability: false,
    mdrrmo_response_status: 'pending',
    severity: '',
    incident_type: '',
    latitude: 14.9161,
    longitude: 121.0389,
    address: 'Bigte Bridge approach, Barangay Bigte',
    location_name: 'Bigte Bridge approach',
    barangay_name: 'Bigte',
    proof_url: null,
    proof_type: null,
    proof_urls: [],
    proof_types: [],
    reporter_type: 'resident',
    reporter_name: 'Maria Santos',
    reporter_phone: '0917 555 0101',
    reporter: { id: 'demo-resident-001', full_name: 'Maria Santos', role: 'resident' },
    barangay_response_notes: '',
    mdrrmo_coordination_notes: '',
    mdrrmo_response_notes: '',
    mdrrmo_dispatch_notes: '',
    mdrrmo_responder_name: null,
    mdrrmo_responded_by: null,
    resolved_notes: null,
    created_at: pendingReportReceivedAt,
    client_submitted_at: pendingReportReceivedAt,
    incident_occurred_at: minutesAgo(39),
    incident_time_precision: 'approximate',
    dispatched_at: null,
    accepted_at: null,
    arrived_at: null,
    resolved_at: null,
    mdrrmo_assignments: [],
    is_demo_data: true,
  },
  {
    id: 'demo-report-fire-responding',
    client_request_id: 'demo-client-request-fire-002',
    lifecycle_revision: 4,
    evidence_status: 'ready',
    type: 'fire',
    title: 'Residential fire near Poblacion market',
    specifics: 'Smoke is visible from a two-storey home.',
    description: 'A residential fire is spreading toward the adjoining house. One older adult is waiting outside and needs assistance.',
    status: 'responding',
    send_to: 'mdrrmo',
    is_escalated: true,
    beyond_barangay_capability: true,
    mdrrmo_response_status: 'responding',
    severity: 'high',
    incident_type: 'fire',
    latitude: 14.9102,
    longitude: 121.0485,
    address: 'Mabini Street, Barangay Poblacion',
    location_name: 'Near Poblacion market',
    barangay_name: 'Poblacion',
    proof_url: null,
    proof_type: null,
    proof_urls: [],
    proof_types: [],
    reporter_type: 'resident',
    reporter_name: 'Joel Reyes',
    reporter_phone: '0917 555 0102',
    reporter: { id: 'demo-resident-002', full_name: 'Joel Reyes', role: 'resident' },
    barangay_response_notes: 'Barangay responders secured the street and helped residents move away from the building.',
    mdrrmo_coordination_notes: 'Escalated to MDRRMO because the fire is spreading to an adjoining home.',
    mdrrmo_response_notes: '[MDRRMO FIELD ASSESSMENT]\nSituation: Fire is active in a two-storey home.\nPeople affected / urgency: One older adult assisted to a safe area; neighboring homes at risk.\nActions taken: Fire crew is en route; barangay team established a safety perimeter.\nRisks / resources: Requesting one additional water tanker.',
    mdrrmo_dispatch_notes: 'Approach from Mabini Street and keep the west lane open for the tanker.',
    mdrrmo_responder_name: 'Fire Responder Carlo Mendoza',
    mdrrmo_responded_by: 'demo-responder-fire-01',
    resolved_notes: null,
    created_at: activeReportReceivedAt,
    client_submitted_at: activeReportReceivedAt,
    incident_occurred_at: activeIncidentTime,
    incident_time_precision: 'exact',
    dispatched_at: activeDispatchedAt,
    accepted_at: activeAcceptedAt,
    arrived_at: null,
    resolved_at: null,
    mdrrmo_assignments: [{
      responder_id: 'demo-responder-fire-01',
      status: 'responding',
      assigned_at: activeDispatchedAt,
      accepted_at: activeAcceptedAt,
      arrived_at: null,
      responder: { full_name: 'Carlo Mendoza', phone: '0917 555 0103' },
    }],
    is_demo_data: true,
  },
  {
    id: 'demo-report-landslide-resolved',
    client_request_id: 'demo-client-request-landslide-003',
    lifecycle_revision: 6,
    evidence_status: 'ready',
    type: 'landslide',
    title: 'Small landslide cleared in San Mateo',
    specifics: 'Mud and rocks blocked one lane after overnight rain.',
    description: 'A small landslide blocked one lane near the hillside. No injuries were reported.',
    status: 'resolved',
    send_to: 'mdrrmo',
    is_escalated: false,
    beyond_barangay_capability: false,
    mdrrmo_response_status: 'resolved',
    severity: 'moderate',
    incident_type: 'other',
    latitude: 14.9242,
    longitude: 121.0567,
    address: 'Hillside Road, Barangay San Mateo',
    location_name: 'Hillside Road',
    barangay_name: 'San Mateo',
    proof_url: null,
    proof_type: null,
    proof_urls: [],
    proof_types: [],
    reporter_type: 'resident',
    reporter_name: 'Liza Cruz',
    reporter_phone: '0917 555 0104',
    reporter: { id: 'demo-resident-003', full_name: 'Liza Cruz', role: 'resident' },
    barangay_response_notes: 'Barangay team closed the affected lane while the crew cleared debris.',
    mdrrmo_coordination_notes: '',
    mdrrmo_response_notes: '[MDRRMO FIELD ASSESSMENT]\nSituation: A small amount of soil and rock covered one lane.\nPeople affected / urgency: No injuries; traffic redirected.\nActions taken: Debris removed and road reopened after inspection.\nRisks / resources: Monitor the slope if rain continues.',
    mdrrmo_dispatch_notes: 'Take the hillside route and bring road-clearing tools.',
    mdrrmo_responder_name: 'Rescue Responder Bea Flores',
    mdrrmo_responded_by: 'demo-responder-rescue-02',
    resolved_notes: 'Debris removed, road inspected, and the lane reopened to traffic.',
    created_at: resolvedReportReceivedAt,
    client_submitted_at: resolvedReportReceivedAt,
    incident_occurred_at: resolvedIncidentTime,
    incident_time_precision: 'approximate',
    dispatched_at: resolvedDispatchedAt,
    accepted_at: resolvedAcceptedAt,
    arrived_at: resolvedArrivedAt,
    resolved_at: resolvedAt,
    mdrrmo_assignments: [{
      responder_id: 'demo-responder-rescue-02',
      status: 'resolved',
      assigned_at: resolvedDispatchedAt,
      accepted_at: resolvedAcceptedAt,
      arrived_at: resolvedArrivedAt,
      resolved_at: resolvedAt,
      responder: { full_name: 'Bea Flores', phone: '0917 555 0105' },
    }],
    is_demo_data: true,
  },
];

export const DEMO_RESPONSE_TASKS = [
  {
    id: 'demo-task-fire-responding',
    title: 'Residential fire near Poblacion market',
    task_type: 'fire_response',
    required_skill: 'Fire response',
    assigned_to: 'demo-responder-fire-01',
    assigned_user: { full_name: 'Carlo Mendoza', role: 'responder' },
    responders: [],
    status: 'accepted',
    created_at: activeDispatchedAt,
    accepted_at: activeAcceptedAt,
    arrived_at: null,
    returning_at: null,
    completed_at: null,
    returned_at: null,
    latitude: 14.9102,
    longitude: 121.0485,
    address: 'Mabini Street, Barangay Poblacion',
    incident: {
      id: 'demo-report-fire-responding',
      title: 'Residential fire near Poblacion market',
      type: 'fire',
      severity: 'high',
      status: 'responding',
      latitude: 14.9102,
      longitude: 121.0485,
      address: 'Mabini Street, Barangay Poblacion',
    },
    report: {
      id: 'demo-report-fire-responding',
      type: 'fire',
      title: 'Fire',
      severity: 'high',
      dispatched_at: activeDispatchedAt,
      resolved_at: null,
    },
    is_demo_data: true,
  },
  {
    id: 'demo-task-landslide-resolved',
    title: 'Small landslide cleared in San Mateo',
    task_type: 'road_clearance',
    required_skill: 'Search and rescue',
    assigned_to: 'demo-responder-rescue-02',
    assigned_user: { full_name: 'Bea Flores', role: 'responder' },
    responders: [],
    status: 'completed',
    created_at: resolvedDispatchedAt,
    accepted_at: resolvedAcceptedAt,
    arrived_at: resolvedArrivedAt,
    returning_at: minutesAgo(105),
    completed_at: resolvedAt,
    returned_at: resolvedReturnedAt,
    latitude: 14.9242,
    longitude: 121.0567,
    address: 'Hillside Road, Barangay San Mateo',
    incident: {
      id: 'demo-report-landslide-resolved',
      title: 'Small landslide cleared in San Mateo',
      type: 'landslide',
      severity: 'moderate',
      status: 'resolved',
      resolved_at: resolvedAt,
      latitude: 14.9242,
      longitude: 121.0567,
      address: 'Hillside Road, Barangay San Mateo',
    },
    report: {
      id: 'demo-report-landslide-resolved',
      type: 'landslide',
      title: 'Road clearance',
      severity: 'moderate',
      dispatched_at: resolvedDispatchedAt,
      resolved_at: resolvedAt,
    },
    is_demo_data: true,
  },
];

export const DEMO_DISPATCH_UNITS = [{
  id: 'demo-unit-fire-response-01',
  name: 'Demo Fire Response Unit 01',
  unit_type: 'Fire and Rescue',
  specialization: 'Fire and Rescue',
  leader_name: 'Carlo Mendoza',
  members: ['Carlo Mendoza · Team lead', 'Jessa Ramos · Firefighter', 'Ramon Dela Cruz · Driver'],
  latitude: 14.9131,
  longitude: 121.0424,
  target_incident_id: 'demo-report-fire-responding',
  target_location: 'Mabini Street, Barangay Poblacion',
  is_demo_data: true,
}];

export const DEMO_RESPONDER_LOCATIONS = [{
  userId: 'demo-responder-fire-01',
  latitude: 14.9131,
  longitude: 121.0424,
  timestamp: Date.now(),
}];
