name: resident_app
description: "NorzAgapay Resident App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  provider: ^6.1.5+1
  location: ^8.0.1
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  camera: ^0.11.1
  connectivity_plus: ^6.1.4
  video_player: ^2.11.1
  socket_io_client: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/NA-icon.png
    - assets/maps/norzagaray_boundary.geojson
